language: node_js
sudo: false
node_js:
  - "6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
before_script:
  - npm install -g mocha
services:
  - mongodb
env:
  - TRAVIS=travis CXX=g++-4.8
